GET http://localhost:3003/books HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDJFODZBNC0zQkY5LTQyRTAtOUM3Mi00QzBFRjg2QzNFRDkiLCJpYXQiOjE2OTg2OTU5MTIsImV4cCI6MTY5ODY5NTk3Mn0.as2euRjItRBUEf_PMr8KgqIEbXQZ46El3kG4OqVUiwU