GET http://localhost:3003/user/borrows/642E86A4-3BF9-42E0-9C72-4C0EF86C3ED9 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDJFODZBNC0zQkY5LTQyRTAtOUM3Mi00QzBFRjg2QzNFRDkiLCJpYXQiOjE2OTYwMjI2MDAsImV4cCI6MTY5NjAyMjY2MH0.-EUYToAGc3YBaKLbejxkQ3yuxizRQ-Ky-ETcE56fHTw